language: python
python:
- 3.6
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
install:
  - conda env update -n base --file environment.yml
script:
  - nosetests --with-coverage --cover-package amtui
  - codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bellockk
  password:
    secure: ZaaTE+cNkFac7lGP9GjaJvJZwhACXMCRTr7wI4r3/KtD/bUnwbIkT1HqC/qjHq4lnUwMNsI09+682MO7S3ifFwbzPXHtgHpTpXF3xEQY94vTki92OqFp2grctHkNIvzTTho+bkVQEGM3BOfZz6Ux4wX1FNT8Qic8qwqs9950M5PVVmV4aw9FrYnQmSsxZNVwfWpYgbt1MlLt/LhasW+ASIMPB82vg0EZM8x9yljgM47cI/bAHvrfv4TcmvzIAeQcVfxmkv26kD/ZsXHeNI57zkAeEJwywQ2f701kg5PlThi5Kgb2rrM4sn6+qFp0RNjYE8/KAc/05NafbO88OjTxsOfDSyKO8A1+fa5GAplTVLdItzPhTHx38lpPIfDqfcH/SncuCkqstVaIoAZAwmr+x5Frm+IMVtTUkBhsOBy//9jkV3goHQ5N7+MpQZHKx4njxsCXxcN+Skz1nXlGMMyqa9trMBkE6W1XZPWi6xHd/tiIz2j2WWFTtOeTg2kfNy2e7sLipyyeAV1TqyN48tth0B6DPQaF2gGdXeS59JIDtqmRQ4I+Uq6anankzpbRrRA6WXKogd8NsDfQqKkrDuEKSrdAbEalYJG6zVI9l64nye45OnkHoxiBL8vi4zZXzVFBzHh4qdrutUa/0TWUngJzkQ++Kf4yy2DLmdxK8Hz7Tqg=
  on:
    tags: true
    repo: bellockk/amtui
    python: 3.6
