language: python
python:
- 3.6
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - rm -fr miniconda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
install:
  - conda env update -n base --file environment.yml
script:
  - nosetests --with-coverage --cover-package amtui
  - codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bellockk
  password:
    secure: Bo+DYfu8WmhkyQCMQRPx4QLgp4ffTHP8fTts0jNmpqireMWLiNxjagVcKotfRmZwkPkEZUaXrA0fz8fL4xwN1KInFadgSte5U2J4gIm7ADpKSt3W8pRnDAR8WWEEPCxGf7GJ8SdRyc025VPI1o19CRGYGmD2TwoO17vAOArLgXbseJ58fPUNFcuGGyjFg+2kSldYIZdNVDfuua3cavkpQdynoX17lRkafLeM6IYCtU9Dkx4w9XLQ9tATQE++Ta6hCJdhVQNey3sD5VmzU4++GPqwu+6/0Em6DOuMreDdBC3AQLSJ9fT2+SzNE40SuoxxCMBK8YfmuLpQtVuuKan/rw5Ptrp/JDL0LQ6Vm2dhB0uJLdb1JvTMUEwnElS0NZIIPQrbWQEl44zS7js1CvRZcctMcwP6Ct8PxkCWazJfPYWb4QFGZpnc0/neh93mCpLt/CcYxnFMPBP/FnD//tmOGQhqPrFHl3XSc7QDdxtAs647MiobzqLjeaRZFxIYm6A7DhrdIv5qULAsftF8c14dViWBbCJx/VwUjtQ8iW1id9MJy3xDLs8RxddkUP2CHo7tZXtrB8kIUmgX7Vs/J8cAjTifNDuWAVYbrH75N50I0XGdaZv5jk0GJnPyGJ4UndY1Hy6UcK4AhTQ81/LbFJfeTxEWSFmBFEzE03k9W7ZfYp8=
  on:
    tags: true
    repo: bellockk/amtui
    python: 3.6
