import os

# Setup local build environment and paths
Import('env')
local_env = env.Clone()
root = os.path.dirname(Dir('.').srcnode().abspath)
media_path = os.path.join(root, 'media')
common_path = os.path.join(root, 'common')

# Build Document
local_env.PrependENVPath('PATH', common_path)
local_env.Append(TEXINPUTS=[common_path, media_path])
pdf = local_env.PDF('document.tex')
install = env.Command(
    'Image.png', pdf, [
        ("convert -trim -density 300 ${SOURCE} "
         "-quality 100 -flatten -sharpen 0x1.0 ${TARGET}"),
        "base64 ${TARGET}"])
Return('install')
